---
title: "test"
author: "MaartenPostuma"
date: "2024-02-22"
output: html_document
runtime: shiny

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
usePackage <- function(p) 
{
  if (!is.element(p, installed.packages()[,1]))
    install.packages(p, dep = TRUE,repos = "https://cloud.r-project.org")
  require(p, character.only = TRUE)
}
# usePackage("rsconnect")
usePackage("ggplot2")
usePackage("ggpubr")
usePackage("knitr")
usePackage("ggdendro")
usePackage("shiny")
usePackage("ggrepel")
usePackage("DT")

```


```{r readData}
dataSet<-read.table("../../results/pcaAll.tsv",h=T)
treeSegments<-read.table("../../results/treeSegmentsAll.tsv",h=T)
treeLabels<-read.table("../../results/treeLabelsAll.tsv",h=T)
popStats<-read.table("../../results/popStatsAll.tsv",h=T)



```


```{r pca, echo=FALSE}
library(shiny)
library(ggplot2)
library(ggrepel)
library(ggpubr)
vars=names(dataSet)

shinyApp(
  ui = fluidPage(
    fluidRow(style = "padding-bottom: 20px;",
             column(4, selectInput('xcol', 'X Variable', vars[3:5],selected = vars[3])),
             column(4, selectInput('ycol', 'Y Variable', vars[3:5],selected = vars[4])),
             column(4, selectInput('maf', 'maf',unique(dataSet$maf))),
             column(4, selectInput('max_missing', 'max_missing',unique(dataSet$max_missing)))
    ),
    fluidRow(
      plotOutput('pca', height = "400px")  
    )
  ),
  
  server = function(input, output, session) {
    
    # Combine the selected variables into a new data frame
    selectedData = reactive({
      dataSet[dataSet$maf==input$maf&dataSet$max_missing==input$max_missing, c(input$xcol, input$ycol,"metaPop","pop","PCA1Var","PCA2Var","PCA3Var")]
    })
    
    
    output$pca = renderPlot(height = 400, {
      ggplot(data=selectedData(),aes(x=selectedData()[,input$xcol],y=selectedData()[,input$ycol],
                                     col=selectedData()[,"metaPop"],label=selectedData()[,"pop"]))+
        theme_pubclean()+
        geom_point()+
        geom_text_repel(col="black")+
        xlab(paste0(input$xcol," (",round(unique(selectedData()[,paste0(input$xcol,"Var")],1)*100),"%)"))+
        ylab(paste0(input$ycol," (",round(unique(selectedData()[,paste0(input$ycol,"Var")],1)*100),"%)"))
      
    })
  },
  
  options = list(height = 500)
)

```

```{r clusters, echo=FALSE}
#You can use this script to create a shiny app of the output of the SNPFiltering, it uses the "filters/pcaAll.tsv" file.
#Either you download this file from the server and run it on your local Rstudio or you do some magic that I do not understand.




library(shiny)
library(ggplot2)
library(ggrepel)
library(ggpubr)
vars=names(treeSegments)

shinyApp(
  ui = fluidPage(
    fluidRow(style = "padding-bottom: 20px;",
             column(4, selectInput('maf', 'maf',unique(treeSegments$maf))),
             column(4, selectInput('max_missing', 'max_missing',unique(treeSegments$max_missing)))
    ),
    fluidRow(
      plotOutput('cluster', height = "400px")  
    )
  ),
  
  server = function(input, output, session) {
    
    # Combine the selected variables into a new data frame
    selectedSegment= reactive({
      treeSegments[treeSegments$maf==input$maf&treeSegments$max_missing==input$max_missing,c("x","y", "xend","yend")]
    })
    
    selectedLabel= reactive({
      treeLabels[treeLabels$maf==input$maf&treeLabels$max_missing==input$max_missing,c("x","y","metaPop","nSNPs","metaPop","pop","label")]
    })
    
    output$cluster = renderPlot(height = 400, {
      ggplot(selectedSegment()) +
              geom_segment(aes(x = selectedSegment()[,"x"], y = selectedSegment()[,"y"], 
                               xend = selectedSegment()[,"xend"], yend=selectedSegment()[,"yend"]))+
              theme_pubr()+coord_cartesian(ylim=c(-3,max(selectedSegment()[,"y"])*1.15))+
            geom_text(data = selectedLabel(), aes(selectedLabel()[,"x"], 
                                                  selectedLabel()[,"y"], 
                                                  label = selectedLabel()[,"label"],
                                                  col=selectedLabel()[,"metaPop"]),
                                                  hjust = 1, angle = 90, size = 5)+
              xlab("")+
              ylab("genetic distance")+
              ggtitle(paste("number of SNPs =",unique(selectedLabel()[,"nSNPs"])))
      
    })
  },
  
  options = list(height = 500)
)

```

```{r, echo=FALSE}
popStats[-c(1,2)]<-round(popStats[-c(1,2)],digit=2)
popStats$maf<-as.factor(popStats$maf)
popStats$max_missing<-as.factor(popStats$max_missing)
datatable(popStats,filter = "top")

```