---
title: "filtering report"
#code-author: MaartenPostuma
#date: 23-07-2019
output:
  html_document:
    df_print: paged
params:
  dir: "vcf/"
  rmd: "report.Rmd"
  args: myargs

#### author: `r system("whoami",inter=T)`
#### date: `r system("date",intern=T)`
---

```{r setup, include=FALSE}

#setwd("./output")
chooseCRANmirror(graphics=FALSE, ind=33)
args <- commandArgs(TRUE)
usePackage <- function(p) 
{
  if (!is.element(p, installed.packages()[,1]))
    install.packages(p, dep = TRUE)
  require(p, character.only = TRUE)
}
usePackage("ggplot2")
usePackage("ggpubr")
usePackage("knitr")
usePackage("ggdendro")
usePackage("ggrepel")
usePackage("rmarkdown")
usePackage("DT")
usePackage("reshape2")
usePackage("grid")
usePackage("geosphere")
usePackage("ggpmisc")
usePackage("tidyr")
options(stringsAsFactors = FALSE)

knitr::opts_chunk$set(echo = FALSE)
options(tinytex.verbose = TRUE)
knitr::opts_knit$set(root.dir = '../../')
```

This report contains all the information needed to make descisions about your filtering steps.

# Filter Steps {.tabset .tabset-fade .tabset-pills}

## First Steps

The distribution of individual missingness

```{r fig.cap="Fig.1: Histogram of the fraction of missingness across individuals, red line indicates the cutoff used in filtering step 2"}
indCoverage<-read.table(paste0(params$args[1],"filters/missingIndvs.imiss"),h=T)
rawCutOff<-system("cat config.yaml | grep 'individual_missingness'| cut -f2 -d :",intern=T)

cutOff<-as.numeric(gsub("[^0-9.-]", "", rawCutOff))
if(cutOff==0.0){
  cutOff<-0.8
}
popMapFilter<-read.table(paste0(params$args[1],"/stacksFiles/popmapFiltered.tsv"))
numberOfIndividuals<-nrow(popMapFilter)
popmap<-read.table(paste0(params$args[1],"/stacksFiles/popmap.tsv"))

ggplot(indCoverage,aes(x=F_MISS))+geom_histogram(col="black",fill="lightblue",binwidth=0.025)+
  ggtitle(paste0(numberOfIndividuals,"out of ",nrow(popmap)))+ylab("fraction missing")+
  theme_light()+geom_vline(xintercept=cutOff,col="red")

```

Below is a list of the samples that were excluded from the analysis
```{r}
popmap$V1[!popmap$V1%in%popMapFilter$V1]

```

```{r,message=FALSE,results='asis',error=TRUE, fig.cap=paste("")}
parameters<-read.table("src/filterAndFigures/paramTest.tsv",h=T)
pcaData<-read.table(paste0(params$args[1],"filters/pcaAll.tsv"),h=T)
treeSegments<-read.table(paste0(params$args[1],"filters/treeSegmentsAll.tsv"),h=T)
treeLabels<-read.table(paste0(params$args[1],"filters/treeLabelsAll.tsv"),h=T)
popStats<-read.table(paste0(params$args[1],"filters/popStatsAll.tsv"),h=T)
fstStats<-read.table(paste0(params$args[1],"filters/fstStatsAll.tsv"),h=T)

for(j in 1:length(unique(parameters$max_missing))){
max_missing<-unique(parameters$max_missing)[j]
cat(paste0("\n\n## Max missing =",max_missing,"{.tabset .tabset-fade .tabset-pills}"))
cat("\n\n### PCA {.tabset .tabset-fade .tabset-pills}\n")
for(i in 1:length(unique(parameters$maf))){
  
maf<-unique(pcaData$maf)[i]
cat("\n\n#### maf =", maf, "\n")

pcaDataSub<-pcaData[pcaData$max_missing==max_missing&pcaData$maf==maf,]  
print(ggplot(pcaDataSub,aes(x=PCA1,y=PCA2,col=metaPop,label=pop))+
  geom_point()+
  geom_text_repel()+
  theme_pubr()+
  xlab(paste0("PCA 1 (",round(mean(pcaDataSub$PCA1Var),2)*100,"%)"))+
  ylab(paste0("PCA 2 (",round(mean(pcaDataSub$PCA2Var),2)*100,"%)"))+
  ggtitle(paste0("PCA Max missing = ",max_missing," maf= ",maf," nSNP=",pcaDataSub$nSNPs)))



}

cat("\n\n### Clusters {.tabset .tabset-fade .tabset-pills}\n")

for(i in 1:length(unique(parameters$maf))){
 maf<-unique(parameters$maf)[i]
 cat("\n\n#### maf = ", maf, "\n")

 treeSegmentsSub<-treeSegments[treeSegments$max_missing==max_missing&treeSegments$maf==maf,]
 treeLabelsSub<-treeLabels[treeLabels$max_missing==max_missing&treeLabels$maf==maf,]

 print(ggplot(treeSegmentsSub) +
   geom_segment(aes(x = x, y = y, xend = xend, yend=yend))+
   theme_pubr()+coord_cartesian(ylim=c(-3,max(treeSegmentsSub$y)*1.15))+
   geom_text(data = treeLabelsSub, aes(x, y, label = label,col=metaPop),
             hjust = 1, angle = 90, size = 5)+
   xlab("")+
   ylab("genetic distance")+
   ggtitle(paste("number of SNPs =",unique(treeLabelsSub$nSNPs),"\n maxMissing =",max_missing,"\n maf =",maf)))
}
cat("\n\n### Fst {.tabset .tabset-fade .tabset-pills}\n")
genDist<-fstStats[fstStats$max_missing==fstStats&pcaData$maf==maf,]  
gen_dendro <- as.dendrogram(hclust(d = as.dist(genDist)))
genDist$pop<-colnames(genDist)
dendro_plot <- ggdendrogram(data = gen_dendro, rotate = TRUE) + 
  theme(axis.text.y = element_text(size = 6))

gen_long <-melt(genDist)
gen_order <- order.dendrogram(gen_dendro)
gen_long$pop <- factor(x = gen_long$pop,
                       levels = colnames(genDist)[gen_order], 
                       ordered = TRUE)
gen_long$variable <- factor(x = gen_long$variable,
                            levels = colnames(genDist)[gen_order], 
                            ordered = TRUE)


heatmap_plot<-ggplot(data = gen_long, aes(x = variable, y = pop)) +
  geom_tile(aes(fill = value)) +
  geom_text(aes(label=round(value,2)))+
  scale_fill_gradient2(low = "#fec44f",mid="#fff7bc",high="#dd1c77")+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "top")



grid.newpage()
print(heatmap_plot, 
      vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))+
      ggitle(paste("mean fst =",mean(gen_long)))
print(dendro_plot, 
      vp = viewport(x = 0.90, y = 0.43, width = 0.2, height = 0.90))

barcodes<-read.table(params$args[2])
if(sum(colnames(barcodes)=="lat")&sum(colnames(barcodes)=="lon")){
cat("\n\n### Isolation by distance {.tabset .tabset-fade .tabset-pills}\n")
 
  geoDistanceDF<-unique(barcodes[,c("pop","lat","lon")])
  row.names(geoDistanceDF)<-geoDistanceDF$pop
  unAvPops<-geoDistanceDF$pop[is.na(geoDistanceDF$lat)|is.na(geoDistanceDF$lon)]
  genDistMantel<-as.dist(genDist[!row.names(genDist)%in%unAvPops,!colnames(genDist)%in%c(unAvPops,"pop")])
  geoDistMantel<-distm(geoDistanceDF[!geoDistanceDF$pop%in%unAvPops,c("lon","lat")],fun = distHaversine)/1000
  distanceDF<-data.frame(geographicalDist=c(as.dist(geoDistMantel)),geneticDist=c(genDistMantel))
  formula <- y ~ x    
  
  print(ggplot(distanceDF,aes(x=geographicalDist,y=geneticDist))+
    geom_point()+
    geom_smooth(method = "lm", formula = formula, se = F) +
    stat_poly_eq(aes(label = paste(..rr.label..)), 
                 label.x = mean(distanceDF$geographicalDist),
                 label.y= mean(distanceDF$geneticDist)-0.5*sd(distanceDF$geneticDist),
                 formula = formula, parse = TRUE, size = 5)+
    stat_fit_glance(method = 'lm',
                    method.args = list(formula = formula),
                    geom = 'text',
                    aes(label = paste("P-value = ", signif(..p.value.., digits = 4), sep = "")),
                    label.x = mean(distanceDF$geographicalDist)+
                      0.5*sd(distanceDF$geographicalDist), 
                    label.y = mean(distanceDF$geneticDist)-1*sd(distanceDF$geneticDist),
                    size = 5)+
    ylab("Fst")+
    xlab("geographical distance (km)"))
}


cat("\n\n### PopStats {.tabset .tabset-fade .tabset-pills}\n")


for(i in 1:length(unique(parameters$maf))){
 maf<-unique(parameters$maf)[i]
 cat("\n\n#### maf = ", maf, "\n")

popStatsSub<-popStats[popStats$max_missing==max_missing&popStats$maf==maf,]
moltenPopStats<-melt(popStatsSub,id.vars=c("pop","max_missing","maf","metaPop"))
for(var in unique(moltenPopStats$variable)){
print(ggplot(moltenPopStats[moltenPopStats$variable==var,],aes(x=pop,y=value,fill=metaPop))+
  geom_col()+
  theme_pubr()+
   theme(axis.text.x = element_text(angle = 45))+
  ggtitle(var)
    )
}



}
}
```

## Popstats

```{r}
popStats<-read.table(paste0(params$args[1],"filters/popStatsAll.tsv"),h=T)
popStats[-c(1,2)]<-round(popStats[-c(1,2)],digit=2)
popStats$maf<-as.factor(popStats$maf)
popStats$max_missing<-as.factor(popStats$max_missing)
datatable(popStats,filter = "top")

```