#In this file you need to specify certain things


#Input folder #The place where you have the rawReads and the barcode file
inputDir: "/path/to/directory/where/reads/and/barcode/file/are"

#Temporary directory, where temporary files are stored. Make sure you have enough space here!
tmpDir: "/path/to/a/place/to/store/temporaryFiles"

#Output dir, directory where all of the output files will be stored
outputDir: "/path/to/directory/where/you/want/to/store/your/output"


#The location of the barcode file 
#This should include the following columns: sample, pop, metaPop, barcode1, barcode2, rawR1, rawR2 seperated by commas 
#And see the readme for an example, and src/demultiplex/barcodeTemplate.csv for a template!
#sample is the sample name,  there cannot be duplicated names otherwise the script will break in unexpected ways. If a sample is in multiple rawreads file consult the readme
#pop is the pop code, 
#metaPop is for assigning aPriori clusters, 
#barcode1 the "first" barcode
#barcode2 the "second" barcode
#rawR1 is the file name of the rawReads_R1 file in which the samples are (if there are multiple illumina indices used)
#rawR2 is the file name of the rawReads_R2 file 

barcodeFile: "nameOfBarcodeFile.csv"










#Parameters (if you want to do something different) otherwise you can leave these blank
param_demultiplex:
  nOligo: ""
  