#In this file you need to specify certain things
#this is the mode and can be three different things:
#Reference (if your species has a reference genome)
#Denovo (if your species does not have a reference genome). This will use stacks but if you want to use this correctly (according to Paris 2017/2022) you will first need to run:
#StacksTest (this generates the plots from the paper to make a decision for which parameters to use in stacks)
mode: "Denovo"
#Input folder #The place where you have the rawReads and the barcode file
inputDir: "data"

#Temporary directory, where temporary files are stored. Make sure you have enough space here!
tmpDir: "/scratch/tmp/"

#Output dir, directory where all of the output files will be stored
outputDir: "results"


#The location of the barcode file 
#This should include the following columns: sample, pop, metaPop, barcode1, barcode2, rawR1, rawR2 seperated by tabs (save as .) 
#And see the readme for an example, and src/demultiplex/barcodeTemplate.csv for a template!
#sample is the sample name,  there cannot be duplicated names otherwise the script will break in unexpected ways. If a sample is in multiple rawreads file consult the readme
#pop is the pop code, 
#metaPop is for assigning aPriori clusters, 
#barcode1 the "first" barcode
#barcode2 the "second" barcode
#rawR1 is the file name of the rawReads_R1 file in which the samples are (if there are multiple illumina indices used)
#rawR2 is the file name of the rawReads_R2 file 
barcodeFile: "barcodes.txt"

#Denovo parameter: The output of the StacksTest run!
M: 4

#Parameters for the filtering: What are the filtering parameters you want to explore?
 
param_filtering:
  individual_missingness: 0.8
  max_missing_range: 0.8
  maf_range: 0.05
  hwe_range: 0
  DP_range: 0

hwe_val: 0
DP_val: 0
maf_val: 0
max_missing_val: 0



#Parameters (if you want to do something different) otherwise you can leave these blank
#Demulitplex parameters: How many oligos are there in your adapters (default = 3)
param_demultiplex:
  nOligo: ""

#For the parameter test how many samples do you need. (Default = 20) (See paris et al. 2017 for specifics)
param_StacksTest:
  nInds: ""
